import { useState, useEffect } from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible';
import { 
  Sparkles, 
  ChevronDown, 
  ChevronUp,
  RefreshCw,
  Brain
} from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

interface TopFeature {
  name: string;
  importance: number;
  value: number | string;
}

interface RiskNarrativeProps {
  riskScore: number;
  topFeatures: TopFeature[];
  patientInfo?: {
    name?: string;
    age?: number;
    diagnosis?: string;
  };
  autoGenerate?: boolean;
}

export const RiskNarrative = ({ 
  riskScore, 
  topFeatures, 
  patientInfo,
  autoGenerate = false 
}: RiskNarrativeProps) => {
  const [isOpen, setIsOpen] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [narrative, setNarrative] = useState<string | null>(null);
  const { toast } = useToast();

  useEffect(() => {
    if (autoGenerate && riskScore > 0.5 && !narrative) {
      generateNarrative();
    }
  }, [autoGenerate, riskScore]);

  const generateNarrative = async () => {
    setIsLoading(true);
    console.log("[Gemini 3] Generating risk narrative...");

    try {
      const response = await fetch(
        `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/generate-risk-narrative`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY}`,
          },
          body: JSON.stringify({ riskScore, topFeatures, patientInfo }),
        }
      );

      if (!response.ok) {
        const error = await response.json();
        throw new Error(error.error || 'Generation failed');
      }

      const data = await response.json();
      console.log("[Gemini 3] Narrative generated:", data);
      
      setNarrative(data.narrative);
      setIsOpen(true);
    } catch (error) {
      console.error("[Gemini 3] Error:", error);
      toast({
        title: "Narrative Generation Failed",
        description: error instanceof Error ? error.message : "Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <Collapsible open={isOpen} onOpenChange={setIsOpen}>
      <Card className="border-primary/10 bg-gradient-to-br from-primary/5 to-transparent">
        <CollapsibleTrigger asChild>
          <div className="p-3 flex items-center justify-between cursor-pointer hover:bg-primary/5 transition-colors rounded-t-lg">
            <div className="flex items-center gap-2">
              <Brain className="h-4 w-4 text-primary" />
              <span className="font-medium text-sm">AI Explanation</span>
              <Badge variant="outline" className="text-xs">
                <Sparkles className="h-3 w-3 mr-1" />
                Gemini 3
              </Badge>
            </div>
            <div className="flex items-center gap-2">
              {!narrative && !isLoading && (
                <Button 
                  size="sm" 
                  variant="ghost"
                  onClick={(e) => {
                    e.stopPropagation();
                    generateNarrative();
                  }}
                  className="h-7 text-xs"
                >
                  Generate
                </Button>
              )}
              {isOpen ? (
                <ChevronUp className="h-4 w-4 text-muted-foreground" />
              ) : (
                <ChevronDown className="h-4 w-4 text-muted-foreground" />
              )}
            </div>
          </div>
        </CollapsibleTrigger>
        
        <CollapsibleContent>
          <CardContent className="pt-0 pb-3">
            {isLoading ? (
              <div className="space-y-2">
                <Skeleton className="h-4 w-full" />
                <Skeleton className="h-4 w-5/6" />
                <Skeleton className="h-4 w-4/6" />
              </div>
            ) : narrative ? (
              <div className="space-y-3">
                <p className="text-sm leading-relaxed">
                  {narrative}
                </p>
                <div className="flex items-center justify-between">
                  <p className="text-xs text-muted-foreground italic">
                    Generated by Gemini 3 • Decision support only
                  </p>
                  <Button
                    size="sm"
                    variant="ghost"
                    onClick={generateNarrative}
                    className="h-7 text-xs gap-1"
                  >
                    <RefreshCw className="h-3 w-3" />
                    Regenerate
                  </Button>
                </div>
              </div>
            ) : (
              <div className="text-center py-4">
                <p className="text-sm text-muted-foreground mb-2">
                  Get a plain-language explanation of this risk prediction
                </p>
                <Button
                  size="sm"
                  onClick={generateNarrative}
                  className="gap-2"
                >
                  <Brain className="h-4 w-4" />
                  Generate Explanation
                </Button>
              </div>
            )}
          </CardContent>
        </CollapsibleContent>
      </Card>
    </Collapsible>
  );
};
